# Site settings
title: Open Arcade
email: brandonpoe@me.com
description: >
  Open Arcade is a collection of ad-free open source games
  that are capable of running in most modern browsers.
  Most games are both desktop and mobile compatible.
baseurl: ""
url: "http://openarcade.github.io"
github_url: "http://github.com/openarcade"
twitter_username: btpoe
github_username:  btpoe

# Build settings
permalink: /games/:title/
markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
